### ISSUE TITLE
Play game with Leap Motion controller

### ISSUE THREAD

**Issue by T1m1** [T1m1/de.htwg.se.monopoly-web#3]
It would be very cool if it would be possible to play the game with the leap motion controller :sunglasses:

**Comment by T1m1** [comment]
Yes, really! And now it's done :dancer: 

Playable with LeapMotion :sunglasses:

**Comment by SteffenGorenflo** [comment]
👍
Am 02.01.2015 16:36 schrieb "Timi" <notifications@github.com>:
